[package]
name = "my_staking_contract"
version = "0.1.0"
edition = "2018"

[dependencies]
solana-program = "1.7.0"
spl-token = { version = "3.2.0", features = ["no-entrypoint"] }

[lib]
crate-type = ["cdylib", "lib"]